version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4-browsers
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: yarn install
  test:
    docker:
      - image: circleci/node:8.11.4-browsers
    steps:
      - checkout
      - run:
        name: Run Eslint
        command: yarn eslint
      - run:
        name: Run Tests
        command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build